[project]
name = "pyreqwest"
version = "0.1.0"
authors = [
    { name = "Markus Sintonen", email = "pyreqwest@gmail.com" }
]
license = {file = "LICENSE"}
requires-python = ">=3.11"
dependencies = [
    "multidict>=6.6.3",
    "yarl>=1.20.1",
]

[dependency-groups]
dev = [
    "maturin==1.9.1",
    "pytest==8.4.1",
    "pytest-asyncio==1.0.0",
    "granian==2.4.1",
    "orjson==3.10.18",
]

[tool.maturin]
module-name = "pyreqwest._pyreqwest"
python-source = "python"
python-packages = ["pyreqwest"]
features = ["pyo3/extension-module"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "session"
asyncio_default_fixture_loop_scope = "session"
