from pathlib import Path
from typing import Self

from pyreqwest.types import HeadersType, Stream

class FormBuilder:
    def __init__(self) -> None: ...
    @property
    def boundary(self) -> str: ...
    def text(self, name: str, value: str) -> Self: ...
    async def file(self, name: str, path: Path) -> Self: ...
    def blocking_file(self, name: str, path: Path) -> Self: ...
    def part(self, name: str, part: PartBuilder) -> Self: ...
    def percent_encode_path_segment(self) -> Self: ...
    def percent_encode_attr_chars(self) -> Self: ...
    def percent_encode_noop(self) -> Self: ...

class PartBuilder:
    @staticmethod
    def from_text(value: str) -> PartBuilder: ...
    @staticmethod
    def from_bytes(value: bytes) -> PartBuilder: ...
    @staticmethod
    def from_stream(stream: Stream) -> PartBuilder: ...
    @staticmethod
    def from_stream_with_length(stream: Stream, length: int) -> PartBuilder: ...
    @staticmethod
    async def from_file(path: Path) -> PartBuilder: ...
    @staticmethod
    def blocking_from_file(path: Path) -> PartBuilder: ...
    def mime_str(self, mime: str) -> Self: ...
    def file_name(self, filename: str) -> Self: ...
    def headers(self, headers: HeadersType) -> Self: ...
