# src/proxy.pyi

from collections.abc import Callable
from typing import Self

from pyreqwest.http import Url
from pyreqwest.types import HeadersType

class Proxy:
    @staticmethod
    def http(url: Url | str) -> Proxy: ...
    @staticmethod
    def https(url: Url | str) -> Proxy: ...
    @staticmethod
    def all(url: Url | str) -> Proxy: ...
    @staticmethod
    def custom(fun: Callable[[Url], Url | str | None]) -> Proxy: ...
    def basic_auth(self, username: str, password: str) -> Self: ...
    def custom_http_auth(self, header_value: str) -> Self: ...
    def headers(self, headers: HeadersType) -> Self: ...
    def no_proxy(self, no_proxy_list: str | None) -> Self: ...
