# src/proxy.pyi

from typing import Callable, Self

from pyreqwest.http import Url
from pyreqwest.types import UrlType, HeadersType


class Proxy:
    @staticmethod
    def http(url: UrlType) -> "Proxy": ...
    @staticmethod
    def https(url: UrlType) -> "Proxy": ...
    @staticmethod
    def all(url: UrlType) -> "Proxy": ...
    @staticmethod
    def custom(fun: Callable[[Url], UrlType | None]) -> "Proxy": ...

    def basic_auth(self, username: str, password: str) -> Self: ...
    def custom_http_auth(self, header_value: str) -> Self: ...
    def headers(self, headers: HeadersType) -> Self: ...
    def no_proxy(self, no_proxy_list: str | None) -> Self: ...
