from typing import Any, Self

from pyreqwest.bytes import Bytes
from pyreqwest.client import Client
from pyreqwest.http import Body, Mime, HeaderMap
from pyreqwest.types import HeadersType, ExtensionsType


class Response:
    @property
    def status(self) -> int: ...
    @status.setter
    def status(self, value: int) -> None: ...
    @property
    def headers(self) -> HeaderMap: ...
    @headers.setter
    def headers(self, headers: HeadersType) -> None: ...
    @property
    def extensions(self) -> dict[str, Any]: ...
    @extensions.setter
    def extensions(self, value: ExtensionsType) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, value: str) -> None: ...

    async def next_chunk(self) -> Bytes | None: ...
    async def bytes(self) -> Bytes: ...
    async def json(self) -> Any: ...
    async def text(self) -> str: ...
    def content_type_mime(self) -> Mime | None: ...
    def error_for_status(self) -> None: ...


class ResponseBuilder:
    async def build(self) -> Response: ...
    def status(self, value: int) -> Self: ...
    def version(self, value: str) -> Self: ...
    def header(self, name: str, value: str) -> Self: ...
    def headers(self, headers: HeadersType) -> Self: ...
    def body(self, body: Body | None) -> Self: ...
    def body_bytes(self, body: bytes) -> Self: ...
    def body_text(self, body: str) -> Self: ...
    def body_json(self, body: Any) -> Self: ...
    def extensions(self, value: ExtensionsType) -> Self: ...

    @staticmethod
    def create_for_mocking() -> "ResponseBuilder":
        """Create a ResponseBuilder instance for mocking purposes. This method is intended for use in tests."""
        pass
