from typing import Any, Self, Mapping

from multidict import CIMultiDict

from pyreqwest.bytes import Bytes
from pyreqwest.http import Body


class Response:
    @property
    def status(self) -> int: ...
    @status.setter
    def status(self, value: int) -> None: ...
    @property
    def headers(self) -> CIMultiDict[str]: ...
    @headers.setter
    def headers(self, value: Mapping[str, str]) -> None: ...
    @property
    def extensions(self) -> dict[str, Any]: ...
    @extensions.setter
    def extensions(self, value: Mapping[str, Any]) -> None: ...
    @property
    def version(self) -> str: ...
    @version.setter
    def version(self, value: str) -> None: ...

    async def next_chunk(self) -> Bytes | None: ...
    async def bytes(self) -> Bytes: ...
    async def json(self) -> Any: ...
    async def text(self) -> str: ...
    def content_type_charset(self) -> str | None: ...
    def error_for_status(self) -> None: ...


class ResponseBuilder:
    def __init__(self) -> None: ...
    async def build(self) -> Response: ...
    def status(self, value: int) -> Self: ...
    def version(self, value: str) -> Self: ...
    def header(self, name: str, value: str) -> Self: ...
    def headers(self, headers: CIMultiDict[str]) -> Self: ...
    def body(self, value: Body | None) -> Self: ...
    def extensions(self, value: Mapping[str, Any] | None) -> Self: ...
