name: Generate Github Pages docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gen-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.13'
      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7

      - name: Build docs
        run: make docs outdir=./docs/dist

      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          folder: ./docs/dist
          target-folder: ${{ github.ref_name == 'main' && '.' || github.ref_name }}
          branch: gh-pages-gen-docs
          single-commit: true
          force: true
          clean: true
          clean-exclude: |
            v*
