class RequestError(Exception): ...

class SendError(RequestError): ...
class SendConnectionError(SendError): ...
class SendBodyError(SendError): ...
class SendTimeoutError(SendError): ...
class PoolTimeoutError(SendTimeoutError): ...

class ReadError(RequestError): ...
class ReadBodyError(ReadError): ...
class ReadTimeoutError(ReadError): ...
